# Generated by Django 4.2.30 on 2026-09-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='next_of_kin_phone',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='current_workstation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='home_subcounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='member_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('PENDING_TREASURER', 'Pending Treasurer Approval'), ('PENDING_DETAILS', 'Pending Additional Details'), ('PENDING_SECRETARY', 'Pending Secretary Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING_TREASURER', max_length=30),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='welfare.memberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='welfare.memberprofile')),
            ],
        ),
    ]
