# Generated by Django 4.2.30 on 2026-09-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0002_remove_memberprofile_next_of_kin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('PENDING_TREASURER', 'Pending Treasurer Approval'), ('PENDING_DETAILS', 'Pending Additional Details'), ('PENDING_SECRETARY', 'Pending Secretary Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected')], default='PENDING_TREASURER', max_length=30),
        ),
    ]
