# Generated by Django 4.2.30 on 2026-09-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0003_alter_memberprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='home_subcounty',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
