# Generated by Django 4.2.30 on 2026-09-23 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welfare', '0004_remove_memberprofile_home_subcounty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('PENDING_TREASURER', 'Pending Treasurer Approval'), ('ACTIVE_INCOMPLETE', 'Active (Missing Details)'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected')], default='PENDING_TREASURER', max_length=30),
        ),
        migrations.CreateModel(
            name='MinuteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('excerpt', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='minutes/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_minutes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
