# Generated by Django 4.2.30 on 2026-09-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0005_alter_memberprofile_status_minuterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
