# Generated by Django 4.2.30 on 2026-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0006_memberprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='home_subcounty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
