# Generated by Django 4.2.30 on 2026-09-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0007_memberprofile_home_subcounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_cases', to='welfare.memberprofile'),
        ),
    ]
