import React, { useState, useContext } from 'react';
import { DatabaseContext } from '../context/DatabaseContext';
import { AuthContext } from '../context/AuthContext';

const MemberDashboard: React.FC = () => {
  const { members, setMembers, cases, contributions, minutes } = useContext(DatabaseContext);
  const { user } = useContext(AuthContext);
  
  const [activeTab, setActiveTab] = useState('PROFILE');
  const [editMode, setEditMode] = useState(false);
  
  // Use the ID from AuthContext, otherwise fallback to the first active incomplete member or default
  const profile = members.find(m => m.id === user?.id) || members[0];

  const handleUpdateProfile = (e: React.FormEvent) => {
    e.preventDefault();
    setEditMode(false);
    
    // If they were ACTIVE_INCOMPLETE and they just filled things out, maybe keep them ACTIVE_INCOMPLETE until Secretary gives Member No, but let's notify.
    alert('Profile updated! Notifications have been sent to the Officials. Your Member No will be generated by the Secretary shortly.');
  };

  const handleDownloadForm = () => {
    const timestamp = new Date().toLocaleString();
    alert(`Downloading Membership Form...\nGenerated on: ${timestamp}`);
  };

  // Derived data
  const myContributions = contributions.filter(c => c.memberId === profile.id);
  const officials = members.filter(m => m.role === 'SECRETARY' || m.role === 'TREASURER');

  const needsDetails = profile.status === 'ACTIVE_INCOMPLETE' || profile.dependents?.length === 0;

  return (
    <div className="bg-white/40 backdrop-blur-xl shadow-2xl border border-white/60 rounded-3xl p-4 md:p-8 relative min-h-[80vh]">
      
      {needsDetails && (
        <div className="mb-6 bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded-r shadow-sm flex items-start">
          <svg className="w-6 h-6 mr-3 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
          <div>
            <h3 className="font-bold text-lg">Action Required: Complete Your Profile</h3>
            <p className="text-sm">Welcome to the Majustwe Welfare Portal! To receive your official Member No. and be fully covered, you must declare your Dependents and Guardians in the Profile tab below.</p>
          </div>
        </div>
      )}

      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
        <div>
          <h2 className="text-3xl font-extrabold text-majustwe-blue drop-shadow-sm">Welcome, {profile.name}</h2>
          <div className="flex items-center space-x-3 mt-2">
            <span className="bg-majustwe-lime text-white px-3 py-1 rounded-full text-sm font-bold shadow-sm">Member No: {profile.memberNo || 'PENDING'}</span>
            <span className={`px-3 py-1 rounded-full text-sm font-bold shadow-sm ${profile.status === 'ACTIVE' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
              Status: {profile.status === 'ACTIVE_INCOMPLETE' ? 'ACTIVE (Missing Details)' : profile.status}
            </span>
            <span className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm font-bold shadow-sm">Type: {profile.type}</span>
          </div>
        </div>
        <button onClick={handleDownloadForm} className="bg-white text-majustwe-blue font-bold px-4 py-2 border border-majustwe-blue rounded-lg shadow-sm hover:bg-blue-50 flex items-center transition-colors">
          <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
          Download Membership Form
        </button>
      </div>

      {/* Tabs */}
      <div className="flex space-x-1 mb-6 border-b border-white/50 overflow-x-auto pb-2">
        {['PROFILE', 'CONTRIBUTIONS', 'MINUTES', 'OFFICIALS'].map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-4 md:px-6 py-3 font-bold text-sm md:text-base rounded-t-xl transition-colors whitespace-nowrap ${
              activeTab === tab 
                ? 'bg-majustwe-blue text-white shadow-md' 
                : 'text-majustwe-blue hover:bg-white/50'
            }`}
          >
            {tab}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="bg-white/60 backdrop-blur-md rounded-b-2xl rounded-tr-2xl p-6 shadow-inner border border-white/80">
        
        {activeTab === 'PROFILE' && (
          <div>
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-xl font-bold text-majustwe-blue">Personal Details</h3>
              {!editMode && (
                <button onClick={() => setEditMode(true)} className="text-majustwe-lime font-bold hover:text-majustwe-darkLime flex items-center bg-white px-3 py-1.5 rounded-md shadow-sm border border-gray-100">
                  <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
                  Edit Details
                </button>
              )}
            </div>

            <form onSubmit={handleUpdateProfile} className="space-y-4 max-w-2xl">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Full Name</label>
                  <input type="text" disabled value={profile.name} className="w-full p-2 bg-gray-100 border border-gray-300 rounded-lg text-gray-600" />
                  <p className="text-xs text-red-500 mt-1">Name cannot be changed.</p>
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Zone</label>
                  <input type="text" disabled value={profile.zone} className="w-full p-2 bg-gray-100 border border-gray-300 rounded-lg text-gray-600" />
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Phone Number</label>
                  <input type="text" disabled={!editMode} value={profile.phone} onChange={e => {
                    const newMembers = members.map(m => m.id === profile.id ? { ...m, phone: e.target.value } : m);
                    setMembers(newMembers);
                  }} className={`w-full p-2 border rounded-lg ${editMode ? 'bg-white border-majustwe-lime focus:ring-majustwe-lime' : 'bg-gray-100 border-gray-300 text-gray-600'}`} />
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Email</label>
                  <input type="email" disabled={!editMode} value={profile.email} onChange={e => {
                    const newMembers = members.map(m => m.id === profile.id ? { ...m, email: e.target.value } : m);
                    setMembers(newMembers);
                  }} className={`w-full p-2 border rounded-lg ${editMode ? 'bg-white border-majustwe-lime focus:ring-majustwe-lime' : 'bg-gray-100 border-gray-300 text-gray-600'}`} />
                </div>
                <div className="md:col-span-2">
                  <label className="block text-sm font-bold text-gray-700 mb-1">Spouse Name</label>
                  <input type="text" disabled={!editMode} value={profile.spouse_name} onChange={e => {
                    const newMembers = members.map(m => m.id === profile.id ? { ...m, spouse_name: e.target.value } : m);
                    setMembers(newMembers);
                  }} className={`w-full p-2 border rounded-lg ${editMode ? 'bg-white border-majustwe-lime focus:ring-majustwe-lime' : 'bg-gray-100 border-gray-300 text-gray-600'}`} />
                </div>
              </div>
              
              {!needsDetails && !editMode && (
                <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-r-lg mt-6">
                  <p className="text-sm text-yellow-800 font-medium"><strong>Note:</strong> Guardian and Dependent details can only be updated by contacting the Secretary directly.</p>
                </div>
              )}

              {/* Phase 2 Details - Editable if needsDetails is true, otherwise Read-only */}
              <div className="mt-8 pt-6 border-t border-gray-200">
                <h4 className="text-lg font-bold text-majustwe-blue mb-4">Official Dependents & Guardians</h4>
                
                {needsDetails && editMode ? (
                  <div className="space-y-6">
                    <div className="bg-red-50 p-4 rounded-xl border border-red-200">
                      <p className="text-sm text-red-800 font-bold mb-4">Please input your dependents and guardians below. You can separate multiple entries with a comma.</p>
                      
                      <label className="block text-sm font-bold text-gray-700 mb-1">Dependents (Names & Relationship)</label>
                      <textarea className="w-full p-2 border rounded-lg bg-white border-majustwe-lime focus:ring-majustwe-lime mb-4" rows={2} placeholder="e.g. Alice Doe (Daughter), Bob Doe (Son)"
                        onChange={e => {
                          const newMembers = members.map(m => m.id === profile.id ? { ...m, dependents: e.target.value.split(',') } : m);
                          setMembers(newMembers);
                        }}
                      ></textarea>

                      <label className="block text-sm font-bold text-gray-700 mb-1">Guardians (Name, Relationship, Phone)</label>
                      <textarea className="w-full p-2 border rounded-lg bg-white border-majustwe-lime focus:ring-majustwe-lime" rows={2} placeholder="e.g. Mark Smith (Brother) - 0722000111"
                        onChange={e => {
                          const newMembers = members.map(m => m.id === profile.id ? { ...m, guardians: e.target.value.split(',') } : m);
                          setMembers(newMembers);
                        }}
                      ></textarea>
                    </div>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="bg-white border border-gray-200 p-4 rounded-xl shadow-sm">
                      <h5 className="font-bold text-gray-800 mb-2 border-b pb-1">Dependents</h5>
                      <ul className="text-sm text-gray-600 list-disc pl-4 space-y-1">
                        {profile.dependents?.map((d: string, i: number) => <li key={i}>{d}</li>)}
                        {(!profile.dependents || profile.dependents.length === 0) && <li className="text-red-500 italic">None declared</li>}
                      </ul>
                    </div>
                    <div className="bg-white border border-gray-200 p-4 rounded-xl shadow-sm">
                      <h5 className="font-bold text-gray-800 mb-2 border-b pb-1">Guardians</h5>
                      <ul className="text-sm text-gray-600 list-disc pl-4 space-y-1">
                        {profile.guardians?.map((g: string, i: number) => <li key={i}>{g}</li>)}
                        {(!profile.guardians || profile.guardians.length === 0) && <li className="text-red-500 italic">None declared</li>}
                      </ul>
                    </div>
                  </div>
                )}
              </div>

              {editMode && (
                <div className="flex space-x-3 pt-4 border-t border-gray-200 mt-6">
                  <button type="submit" className="bg-majustwe-lime text-white font-bold py-2 px-6 rounded-lg shadow hover:bg-majustwe-darkLime">Save Changes</button>
                  <button type="button" onClick={() => setEditMode(false)} className="bg-gray-200 text-gray-800 font-bold py-2 px-6 rounded-lg hover:bg-gray-300">Cancel</button>
                </div>
              )}
            </form>
          </div>
        )}

        {activeTab === 'CONTRIBUTIONS' && (
          <div>
            <h3 className="text-xl font-bold text-majustwe-blue mb-6">Financial Contributions</h3>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50/50">
                  <tr>
                    <th className="px-4 py-3 text-left text-sm font-semibold text-gray-900">Case/Event</th>
                    <th className="px-4 py-3 text-left text-sm font-semibold text-gray-900">Required (Ksh)</th>
                    <th className="px-4 py-3 text-left text-sm font-semibold text-gray-900">Paid (Ksh)</th>
                    <th className="px-4 py-3 text-left text-sm font-semibold text-gray-900">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {myContributions.map(c => {
                    const caseObj = cases.find(caseItem => caseItem.id === c.caseId);
                    if (!caseObj) return null;
                    return (
                      <tr key={c.id}>
                        <td className="whitespace-nowrap px-4 py-3 text-sm font-medium text-gray-800">{caseObj.title}</td>
                        <td className="whitespace-nowrap px-4 py-3 text-sm text-gray-600">{caseObj.requiredAmount}</td>
                        <td className="whitespace-nowrap px-4 py-3 text-sm text-gray-600">{c.paid}</td>
                        <td className="whitespace-nowrap px-4 py-3 text-sm">
                          <span className={`px-2 py-1 text-xs font-bold rounded-full ${c.status === 'CLEARED' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {c.status}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                  {myContributions.length === 0 && (
                    <tr><td colSpan={4} className="px-4 py-3 text-center text-gray-500 italic">No contributions found.</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {activeTab === 'MINUTES' && (
          <div>
            <h3 className="text-xl font-bold text-majustwe-blue mb-6">Welfare Records & Minutes</h3>
            <div className="space-y-4">
              {minutes.map(m => (
                <div key={m.id} className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm hover:shadow transition-shadow">
                  <div className="flex justify-between items-start mb-2">
                    <h4 className="font-bold text-lg text-gray-900">{m.title}</h4>
                    <span className="text-xs font-bold text-gray-500 bg-gray-100 px-2 py-1 rounded">{m.date}</span>
                  </div>
                  <p className="text-gray-600 text-sm mb-3">{m.excerpt}</p>
                  <button className="text-majustwe-blue font-bold text-sm hover:underline flex items-center">
                    <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                    Download Full Record
                  </button>
                </div>
              ))}
              {minutes.length === 0 && <p className="text-gray-500 italic">No official records have been published yet.</p>}
            </div>
          </div>
        )}

        {activeTab === 'OFFICIALS' && (
          <div>
            <h3 className="text-xl font-bold text-majustwe-blue mb-6">Welfare Officials Directory</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {officials.map((o) => (
                <div key={o.id} className="bg-gradient-to-r from-majustwe-blue/5 to-transparent border border-blue-100 p-6 rounded-2xl flex items-center space-x-4">
                  <div className="w-12 h-12 bg-majustwe-blue text-white rounded-full flex items-center justify-center font-bold text-xl">
                    {o.name.charAt(0)}
                  </div>
                  <div>
                    <p className="text-xs font-bold text-majustwe-lime uppercase tracking-wider">{o.role}</p>
                    <p className="text-lg font-bold text-gray-900">{o.name}</p>
                    <p className="text-sm text-gray-600 font-medium mt-1">📞 {o.phone}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
      </div>
    </div>
  );
};

export default MemberDashboard;
